### ISSUE TITLE
Sette opp https

### ISSUE THREAD

**Issue by henrist** [cybrairai/okonomi#6]
Foreslår å sette opp et sertifikat fra http://www.startssl.com/

Se også https://www.digitalocean.com/community/tutorials/how-to-set-up-multiple-ssl-certificates-on-one-ip-with-nginx-on-ubuntu-12-04 for hvordan dette kan settes opp på serveren

**Comment by matsasc** [comment]
Kryptering er en fin ting

**Comment by henrist** [comment]
Sertifikat satt opp for internt.cyb.no.
